# Generated by Django 2.1 on 2018-09-06 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('prize', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_teams', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='League_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('team_name', models.CharField(max_length=40)),
                ('bid', models.IntegerField(blank=True, default=300)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=40, null=True)),
                ('filled', models.IntegerField(default=0)),
                ('current', models.BooleanField(default=True)),
                ('league_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.League_Type')),
                ('leauge_user', models.ManyToManyField(through='fantasy.League_Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=2)),
                ('jersey', models.IntegerField()),
                ('height', models.CharField(max_length=4)),
                ('weight', models.IntegerField()),
                ('total_draft_positions', models.IntegerField(default=0)),
                ('total_number_drafts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing', models.IntegerField()),
                ('rushing', models.IntegerField()),
                ('receiving', models.IntegerField()),
                ('catches', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.BooleanField(default=False)),
                ('league_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.League_Users')),
                ('leagues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Leagues')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Players')),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Players')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
                ('mascot', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.Teams'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='players',
            field=models.ManyToManyField(through='fantasy.Rosters', to='fantasy.Players'),
        ),
        migrations.AddField(
            model_name='league_users',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Leagues'),
        ),
        migrations.AddField(
            model_name='league_users',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rosters',
            unique_together={('players', 'leagues')},
        ),
        migrations.AlterUniqueTogether(
            name='league_users',
            unique_together={('users', 'league')},
        ),
    ]
