# Generated by Django 2.1 on 2018-09-09 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy', '0002_auto_20180907_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Players')),
            ],
        ),
        migrations.CreateModel(
            name='Rankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my rankings', max_length=12)),
                ('league_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.League_Type')),
                ('players', models.ManyToManyField(through='fantasy.Player_Rank', to='fantasy.Players')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='rosters',
            old_name='players',
            new_name='player',
        ),
        migrations.AlterUniqueTogether(
            name='rosters',
            unique_together={('player', 'leagues')},
        ),
        migrations.AddField(
            model_name='player_rank',
            name='ranking_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Rankings'),
        ),
    ]
