# Generated by Django 2.1 on 2018-09-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_auto_20180909_0225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='points',
        ),
        migrations.AddField(
            model_name='players',
            name='phase',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='Interceptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='TDs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='fumbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='kick_return',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='passing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='punt_return',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='receiving',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='rushing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='sacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='safetys',
            field=models.IntegerField(default=0),
        ),
    ]
