# Generated by Django 2.1 on 2018-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_auto_20180909_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(max_length=3),
        ),
    ]
