# Generated by Django 2.1 on 2018-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_auto_20180909_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankings',
            name='league_type',
            field=models.CharField(max_length=10),
        ),
    ]
