# Generated by Django 2.1 on 2018-09-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_auto_20180909_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='week',
        ),
    ]
