# Generated by Django 2.1 on 2018-09-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0009_rosters_drafted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosters',
            name='league_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.League_Users'),
        ),
    ]
