# Generated by Django 2.1.1 on 2018-09-24 16:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy', '0010_auto_20180916_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagues',
            old_name='leauge_user',
            new_name='league_user',
        ),
        migrations.AlterUniqueTogether(
            name='player_rank',
            unique_together={('player', 'ranking_list')},
        ),
        migrations.AlterUniqueTogether(
            name='rankings',
            unique_together={('user', 'league_type')},
        ),
    ]
