# Generated by Django 2.1.1 on 2018-09-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_auto_20180924_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_users',
            name='draft_position',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
