# Generated by Django 2.1.1 on 2018-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_fantasy_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='bye_week',
            field=models.CharField(default='-1', max_length=2),
        ),
    ]
