# Generated by Django 2.1.1 on 2018-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0014_players_bye_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league_users',
            name='number',
        ),
        migrations.AddField(
            model_name='fantasy_points',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league_users',
            name='franchise',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
