# Generated by Django 2.1.1 on 2018-09-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0015_auto_20180927_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_users',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
