# Generated by Django 2.1.1 on 2018-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0016_league_users_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_users',
            name='franchise',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
