# Generated by Django 2.1.1 on 2018-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0017_auto_20180927_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_users',
            name='franchise',
            field=models.IntegerField(default=0),
        ),
    ]
