# Generated by Django 2.1.1 on 2018-09-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0019_auto_20180927_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Leagues')),
                ('league_user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_user1', to='fantasy.League_Users')),
                ('league_user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_user2', to='fantasy.League_Users')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='fantasy.Rosters')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='fantasy.Rosters')),
            ],
        ),
    ]
