# Generated by Django 2.1.1 on 2018-10-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0020_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fantasy_points',
            old_name='Interceptions',
            new_name='def_interceptions',
        ),
        migrations.RenameField(
            model_name='fantasy_points',
            old_name='kick_return',
            new_name='fumble_recovery',
        ),
        migrations.RenameField(
            model_name='fantasy_points',
            old_name='passing',
            new_name='passing_interceptions',
        ),
        migrations.RenameField(
            model_name='fantasy_points',
            old_name='punt_return',
            new_name='passing_tds',
        ),
        migrations.RenameField(
            model_name='fantasy_points',
            old_name='receiving',
            new_name='passing_yards',
        ),
        migrations.RenameField(
            model_name='fantasy_points',
            old_name='rushing',
            new_name='receiving_tds',
        ),
        migrations.AddField(
            model_name='fantasy_points',
            name='receiving_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasy_points',
            name='return_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasy_points',
            name='rushing_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasy_points',
            name='rushing_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fantasy_points',
            name='two_pt',
            field=models.IntegerField(default=0),
        ),
    ]
