# Generated by Django 2.1.1 on 2018-10-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0023_auto_20181003_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fantasy_points',
            old_name='total_point',
            new_name='total_points',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='passing_yard',
            new_name='passing_yards',
        ),
    ]
