# Generated by Django 2.1.1 on 2018-10-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0024_auto_20181003_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasy_points',
            name='total_points',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
