# Generated by Django 2.1.1 on 2018-10-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0025_auto_20181003_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasy_points',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
