# Generated by Django 2.1.1 on 2018-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0026_auto_20181003_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_users',
            name='ties',
            field=models.IntegerField(default=0),
        ),
    ]
